name: build on mac

on: [push]

jobs:
  build:
    runs-on: osx
    steps:
    - uses: actions/checkout@v2
    - name: build gtk app
      run: |
        ./setup.sh
        make
        # check
        ls -l mini
