name: build on windows10

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: build gtk app
      run: |
        ./setup.sh
        export PKG_CONFIG_PATH=/mingw64/lib/pkgconfig:$PKG_CONFIG_PATH
        make
        # check
        ls -l mini
