name: build on windows10

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: build lablgtk
      run: |
        ./setup.sh
        make
        # check
        ls -l mini
      env:
        OCAML_VERSION: 4.11
        TRAVIS_OS_NAME: linux
        TRAVIS_DIST: focal
